// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3038b1f8defba3b2152d60a8ee0ca09feed194de2a8c35fc30f910ea59122e3e'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Approval: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly approverId: CodecTypes['pg/int4@1']['output'];
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED';
      readonly reason: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Booking: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly venueId: CodecTypes['pg/int4@1']['output'];
      readonly amount: CodecTypes['pg/int4@1']['output'];
      readonly taxAmount: CodecTypes['pg/int4@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly paymentStatus: 'PENDING' | 'PAID' | 'FAILED';
      readonly razorpayOrderId: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Company: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly Event: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly companyId: CodecTypes['pg/int4@1']['output'];
      readonly createdById: CodecTypes['pg/int4@1']['output'];
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly attendees: CodecTypes['pg/int4@1']['output'];
      readonly budget: CodecTypes['pg/int4@1']['output'];
      readonly diet: CodecTypes['pg/text@1']['output'];
      readonly status: 'DRAFT' | 'REQUESTED' | 'APPROVED' | 'REJECTED' | 'BOOKED';
    };
    readonly Invoice: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly bookingId: CodecTypes['pg/int4@1']['output'];
      readonly pdfUrl: CodecTypes['pg/text@1']['output'];
      readonly gstin: CodecTypes['pg/text@1']['output'];
    };
    readonly Policy: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly companyId: CodecTypes['pg/int4@1']['output'];
      readonly maxBudget: CodecTypes['pg/int4@1']['output'];
      readonly perPersonCap: CodecTypes['pg/int4@1']['output'];
      readonly allowedCities: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly approverRole: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly clerkId: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
      readonly companyId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly Venue: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly companyId: CodecTypes['pg/int4@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly capacity: CodecTypes['pg/int4@1']['output'];
      readonly cuisine: CodecTypes['pg/text@1']['output'];
      readonly priceBand: CodecTypes['pg/text@1']['output'];
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly rating: CodecTypes['pg/float8@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Approval: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly approverId: CodecTypes['pg/int4@1']['input'];
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED';
      readonly reason: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Booking: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly venueId: CodecTypes['pg/int4@1']['input'];
      readonly amount: CodecTypes['pg/int4@1']['input'];
      readonly taxAmount: CodecTypes['pg/int4@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly paymentStatus: 'PENDING' | 'PAID' | 'FAILED';
      readonly razorpayOrderId: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Company: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly Event: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly companyId: CodecTypes['pg/int4@1']['input'];
      readonly createdById: CodecTypes['pg/int4@1']['input'];
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly attendees: CodecTypes['pg/int4@1']['input'];
      readonly budget: CodecTypes['pg/int4@1']['input'];
      readonly diet: CodecTypes['pg/text@1']['input'];
      readonly status: 'DRAFT' | 'REQUESTED' | 'APPROVED' | 'REJECTED' | 'BOOKED';
    };
    readonly Invoice: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly bookingId: CodecTypes['pg/int4@1']['input'];
      readonly pdfUrl: CodecTypes['pg/text@1']['input'];
      readonly gstin: CodecTypes['pg/text@1']['input'];
    };
    readonly Policy: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly companyId: CodecTypes['pg/int4@1']['input'];
      readonly maxBudget: CodecTypes['pg/int4@1']['input'];
      readonly perPersonCap: CodecTypes['pg/int4@1']['input'];
      readonly allowedCities: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly approverRole: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly clerkId: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
      readonly companyId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly Venue: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly companyId: CodecTypes['pg/int4@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly capacity: CodecTypes['pg/int4@1']['input'];
      readonly cuisine: CodecTypes['pg/text@1']['input'];
      readonly priceBand: CodecTypes['pg/text@1']['input'];
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly rating: CodecTypes['pg/float8@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly approval: {
      readonly approverId: CodecTypes['pg/int4@1']['output'];
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly reason: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED';
    };
    readonly booking: {
      readonly amount: CodecTypes['pg/int4@1']['output'];
      readonly currency: CodecTypes['pg/text@1']['output'];
      readonly eventId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly paymentStatus: 'PENDING' | 'PAID' | 'FAILED';
      readonly razorpayOrderId: CodecTypes['pg/text@1']['output'] | null;
      readonly taxAmount: CodecTypes['pg/int4@1']['output'];
      readonly venueId: CodecTypes['pg/int4@1']['output'];
    };
    readonly company: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly slug: CodecTypes['pg/text@1']['output'];
    };
    readonly event: {
      readonly attendees: CodecTypes['pg/int4@1']['output'];
      readonly budget: CodecTypes['pg/int4@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly companyId: CodecTypes['pg/int4@1']['output'];
      readonly createdById: CodecTypes['pg/int4@1']['output'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly diet: CodecTypes['pg/text@1']['output'];
      readonly eventType: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly status: 'DRAFT' | 'REQUESTED' | 'APPROVED' | 'REJECTED' | 'BOOKED';
    };
    readonly invoice: {
      readonly bookingId: CodecTypes['pg/int4@1']['output'];
      readonly gstin: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly pdfUrl: CodecTypes['pg/text@1']['output'];
    };
    readonly policy: {
      readonly allowedCities: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly approverRole: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
      readonly companyId: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly maxBudget: CodecTypes['pg/int4@1']['output'];
      readonly perPersonCap: CodecTypes['pg/int4@1']['output'];
    };
    readonly user: {
      readonly clerkId: CodecTypes['pg/text@1']['output'];
      readonly companyId: CodecTypes['pg/int4@1']['output'] | null;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
    };
    readonly venue: {
      readonly capacity: CodecTypes['pg/int4@1']['output'];
      readonly city: CodecTypes['pg/text@1']['output'];
      readonly companyId: CodecTypes['pg/int4@1']['output'];
      readonly cuisine: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly priceBand: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/float8@1']['output'];
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly approval: {
      readonly approverId: CodecTypes['pg/int4@1']['input'];
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly reason: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'PENDING' | 'APPROVED' | 'REJECTED';
    };
    readonly booking: {
      readonly amount: CodecTypes['pg/int4@1']['input'];
      readonly currency: CodecTypes['pg/text@1']['input'];
      readonly eventId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly paymentStatus: 'PENDING' | 'PAID' | 'FAILED';
      readonly razorpayOrderId: CodecTypes['pg/text@1']['input'] | null;
      readonly taxAmount: CodecTypes['pg/int4@1']['input'];
      readonly venueId: CodecTypes['pg/int4@1']['input'];
    };
    readonly company: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly slug: CodecTypes['pg/text@1']['input'];
    };
    readonly event: {
      readonly attendees: CodecTypes['pg/int4@1']['input'];
      readonly budget: CodecTypes['pg/int4@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly companyId: CodecTypes['pg/int4@1']['input'];
      readonly createdById: CodecTypes['pg/int4@1']['input'];
      readonly dateTime: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly diet: CodecTypes['pg/text@1']['input'];
      readonly eventType: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly status: 'DRAFT' | 'REQUESTED' | 'APPROVED' | 'REJECTED' | 'BOOKED';
    };
    readonly invoice: {
      readonly bookingId: CodecTypes['pg/int4@1']['input'];
      readonly gstin: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly pdfUrl: CodecTypes['pg/text@1']['input'];
    };
    readonly policy: {
      readonly allowedCities: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly approverRole: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
      readonly companyId: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly maxBudget: CodecTypes['pg/int4@1']['input'];
      readonly perPersonCap: CodecTypes['pg/int4@1']['input'];
    };
    readonly user: {
      readonly clerkId: CodecTypes['pg/text@1']['input'];
      readonly companyId: CodecTypes['pg/int4@1']['input'] | null;
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
    };
    readonly venue: {
      readonly capacity: CodecTypes['pg/int4@1']['input'];
      readonly city: CodecTypes['pg/text@1']['input'];
      readonly companyId: CodecTypes['pg/int4@1']['input'];
      readonly cuisine: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly priceBand: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/float8@1']['input'];
      readonly tags: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
    };
  };
};

export namespace Models {
  export type public_Company = {
    id: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    slug: CodecTypes['pg/text@1']['output'];
    events: public_Event[];
    policies: public_Policy[];
    users: public_User[];
    venues: public_Venue[];
    readonly [RelationKeys]?: 'events' | 'policies' | 'users' | 'venues';
  };
  export type public_User = {
    id: CodecTypes['pg/int4@1']['output'];
    clerkId: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    role: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
    companyId: CodecTypes['pg/int4@1']['output'] | null;
    approvals: public_Approval[];
    company: public_Company | null;
    events: public_Event[];
    readonly [RelationKeys]?: 'approvals' | 'company' | 'events';
  };
  export type public_Event = {
    id: CodecTypes['pg/int4@1']['output'];
    companyId: CodecTypes['pg/int4@1']['output'];
    createdById: CodecTypes['pg/int4@1']['output'];
    eventType: CodecTypes['pg/text@1']['output'];
    city: CodecTypes['pg/text@1']['output'];
    dateTime: CodecTypes['pg/timestamptz-string@1']['output'];
    attendees: CodecTypes['pg/int4@1']['output'];
    budget: CodecTypes['pg/int4@1']['output'];
    diet: CodecTypes['pg/text@1']['output'];
    status: 'DRAFT' | 'REQUESTED' | 'APPROVED' | 'REJECTED' | 'BOOKED';
    approvals: public_Approval[];
    bookings: public_Booking[];
    company: public_Company;
    createdBy: public_User;
    readonly [RelationKeys]?: 'approvals' | 'bookings' | 'company' | 'createdBy';
  };
  export type public_Venue = {
    id: CodecTypes['pg/int4@1']['output'];
    companyId: CodecTypes['pg/int4@1']['output'];
    city: CodecTypes['pg/text@1']['output'];
    capacity: CodecTypes['pg/int4@1']['output'];
    cuisine: CodecTypes['pg/text@1']['output'];
    priceBand: CodecTypes['pg/text@1']['output'];
    tags: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    rating: CodecTypes['pg/float8@1']['output'];
    bookings: public_Booking[];
    company: public_Company;
    readonly [RelationKeys]?: 'bookings' | 'company';
  };
  export type public_Policy = {
    id: CodecTypes['pg/int4@1']['output'];
    companyId: CodecTypes['pg/int4@1']['output'];
    maxBudget: CodecTypes['pg/int4@1']['output'];
    perPersonCap: CodecTypes['pg/int4@1']['output'];
    allowedCities: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    approverRole: 'ADMIN' | 'REQUESTER' | 'APPROVER' | 'FINANCE';
    company: public_Company;
    readonly [RelationKeys]?: 'company';
  };
  export type public_Approval = {
    id: CodecTypes['pg/int4@1']['output'];
    eventId: CodecTypes['pg/int4@1']['output'];
    approverId: CodecTypes['pg/int4@1']['output'];
    status: 'PENDING' | 'APPROVED' | 'REJECTED';
    reason: CodecTypes['pg/text@1']['output'] | null;
    approver: public_User;
    event: public_Event;
    readonly [RelationKeys]?: 'approver' | 'event';
  };
  export type public_Booking = {
    id: CodecTypes['pg/int4@1']['output'];
    eventId: CodecTypes['pg/int4@1']['output'];
    venueId: CodecTypes['pg/int4@1']['output'];
    amount: CodecTypes['pg/int4@1']['output'];
    taxAmount: CodecTypes['pg/int4@1']['output'];
    currency: CodecTypes['pg/text@1']['output'];
    paymentStatus: 'PENDING' | 'PAID' | 'FAILED';
    razorpayOrderId: CodecTypes['pg/text@1']['output'] | null;
    event: public_Event;
    invoice: public_Invoice | null;
    venue: public_Venue;
    readonly [RelationKeys]?: 'event' | 'invoice' | 'venue';
  };
  export type public_Invoice = {
    id: CodecTypes['pg/int4@1']['output'];
    bookingId: CodecTypes['pg/int4@1']['output'];
    pdfUrl: CodecTypes['pg/text@1']['output'];
    gstin: CodecTypes['pg/text@1']['output'];
    booking: public_Booking;
    readonly [RelationKeys]?: 'booking';
  };
}

export declare const models: {
  public: {
    Company: Models.public_Company;
    User: Models.public_User;
    Event: Models.public_Event;
    Venue: Models.public_Venue;
    Policy: Models.public_Policy;
    Approval: Models.public_Approval;
    Booking: Models.public_Booking;
    Invoice: Models.public_Invoice;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly approval: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly eventId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly approverId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly reason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'approval_eventId_idx_6a266d47';
                  readonly prefix: 'approval_eventId_idx';
                  readonly columns: readonly ['eventId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'approval_approverId_idx_a4f46e61';
                  readonly prefix: 'approval_approverId_idx';
                  readonly columns: readonly ['approverId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'approval';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'approval';
                    readonly columns: readonly ['approverId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly booking: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly eventId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly venueId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly amount: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly taxAmount: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly currency: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly paymentStatus: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly razorpayOrderId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'booking_eventId_idx_6a266d47';
                  readonly prefix: 'booking_eventId_idx';
                  readonly columns: readonly ['eventId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_venueId_idx_b49e8dab';
                  readonly prefix: 'booking_venueId_idx';
                  readonly columns: readonly ['venueId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['venueId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'venue';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly company: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly slug: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['slug'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly event: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly companyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdById: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly eventType: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly dateTime: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly attendees: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly budget: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly diet: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'DRAFT'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'event_companyId_idx_33acc5ed';
                  readonly prefix: 'event_companyId_idx';
                  readonly columns: readonly ['companyId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'event_createdById_idx_8bf640ed';
                  readonly prefix: 'event_createdById_idx';
                  readonly columns: readonly ['createdById'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['companyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'company';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['createdById'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly invoice: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly bookingId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly pdfUrl: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly gstin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['bookingId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'invoice';
                    readonly columns: readonly ['bookingId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly policy: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly companyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly maxBudget: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly perPersonCap: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly allowedCities: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly approverRole: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'policy_companyId_idx_33acc5ed';
                  readonly prefix: 'policy_companyId_idx';
                  readonly columns: readonly ['companyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'policy';
                    readonly columns: readonly ['companyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'company';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly clerkId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly companyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['clerkId'] },
                { readonly columns: readonly ['email'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'user_companyId_idx_33acc5ed';
                  readonly prefix: 'user_companyId_idx';
                  readonly columns: readonly ['companyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['companyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'company';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly venue: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly companyId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly city: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly capacity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly cuisine: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly priceBand: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tags: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'venue_companyId_idx_33acc5ed';
                  readonly prefix: 'venue_companyId_idx';
                  readonly columns: readonly ['companyId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'venue';
                    readonly columns: readonly ['companyId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'company';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly ApprovalStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'APPROVED', 'REJECTED'];
            };
            readonly EventStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['DRAFT', 'REQUESTED', 'APPROVED', 'REJECTED', 'BOOKED'];
            };
            readonly PaymentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'PAID', 'FAILED'];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'REQUESTER', 'APPROVER', 'FINANCE'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly company: { readonly namespace: 'public' & NamespaceId; readonly model: 'Company' };
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly event: { readonly namespace: 'public' & NamespaceId; readonly model: 'Event' };
    readonly venue: { readonly namespace: 'public' & NamespaceId; readonly model: 'Venue' };
    readonly policy: { readonly namespace: 'public' & NamespaceId; readonly model: 'Policy' };
    readonly approval: { readonly namespace: 'public' & NamespaceId; readonly model: 'Approval' };
    readonly booking: { readonly namespace: 'public' & NamespaceId; readonly model: 'Booking' };
    readonly invoice: { readonly namespace: 'public' & NamespaceId; readonly model: 'Invoice' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Approval: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly approverId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly reason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly approver: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['approverId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'approval';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly eventId: { readonly column: 'eventId' };
                readonly approverId: { readonly column: 'approverId' };
                readonly status: { readonly column: 'status' };
                readonly reason: { readonly column: 'reason' };
              };
            };
          };
          readonly Booking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly venueId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly taxAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentStatus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly razorpayOrderId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly invoice: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Invoice';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['bookingId'];
                };
              };
              readonly venue: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venue';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['venueId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'booking';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly eventId: { readonly column: 'eventId' };
                readonly venueId: { readonly column: 'venueId' };
                readonly amount: { readonly column: 'amount' };
                readonly taxAmount: { readonly column: 'taxAmount' };
                readonly currency: { readonly column: 'currency' };
                readonly paymentStatus: { readonly column: 'paymentStatus' };
                readonly razorpayOrderId: { readonly column: 'razorpayOrderId' };
              };
            };
          };
          readonly Company: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['companyId'];
                };
              };
              readonly policies: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Policy';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['companyId'];
                };
              };
              readonly users: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['companyId'];
                };
              };
              readonly venues: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venue';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['companyId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'company';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly slug: { readonly column: 'slug' };
              };
            };
          };
          readonly Event: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly companyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdById: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly eventType: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dateTime: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly attendees: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly budget: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly diet: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly approvals: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Approval';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
              readonly company: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Company';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['companyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly createdBy: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['createdById'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly companyId: { readonly column: 'companyId' };
                readonly createdById: { readonly column: 'createdById' };
                readonly eventType: { readonly column: 'eventType' };
                readonly city: { readonly column: 'city' };
                readonly dateTime: { readonly column: 'dateTime' };
                readonly attendees: { readonly column: 'attendees' };
                readonly budget: { readonly column: 'budget' };
                readonly diet: { readonly column: 'diet' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Invoice: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly bookingId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly pdfUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly gstin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly booking: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['bookingId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'invoice';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bookingId: { readonly column: 'bookingId' };
                readonly pdfUrl: { readonly column: 'pdfUrl' };
                readonly gstin: { readonly column: 'gstin' };
              };
            };
          };
          readonly Policy: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly companyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly maxBudget: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly perPersonCap: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly allowedCities: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly approverRole: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly company: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Company';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['companyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'policy';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly companyId: { readonly column: 'companyId' };
                readonly maxBudget: { readonly column: 'maxBudget' };
                readonly perPersonCap: { readonly column: 'perPersonCap' };
                readonly allowedCities: { readonly column: 'allowedCities' };
                readonly approverRole: { readonly column: 'approverRole' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly clerkId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly companyId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly approvals: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Approval';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['approverId'];
                };
              };
              readonly company: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Company';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['companyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['createdById'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clerkId: { readonly column: 'clerkId' };
                readonly email: { readonly column: 'email' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly companyId: { readonly column: 'companyId' };
              };
            };
          };
          readonly Venue: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly companyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly city: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly capacity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly cuisine: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly priceBand: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['venueId'];
                };
              };
              readonly company: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Company';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['companyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'venue';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly companyId: { readonly column: 'companyId' };
                readonly city: { readonly column: 'city' };
                readonly capacity: { readonly column: 'capacity' };
                readonly cuisine: { readonly column: 'cuisine' };
                readonly priceBand: { readonly column: 'priceBand' };
                readonly tags: { readonly column: 'tags' };
                readonly rating: { readonly column: 'rating' };
              };
            };
          };
        };
        readonly enum: {
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'REQUESTER'; readonly value: 'REQUESTER' },
              { readonly name: 'APPROVER'; readonly value: 'APPROVER' },
              { readonly name: 'FINANCE'; readonly value: 'FINANCE' },
            ];
          };
          readonly EventStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'DRAFT'; readonly value: 'DRAFT' },
              { readonly name: 'REQUESTED'; readonly value: 'REQUESTED' },
              { readonly name: 'APPROVED'; readonly value: 'APPROVED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
              { readonly name: 'BOOKED'; readonly value: 'BOOKED' },
            ];
          };
          readonly ApprovalStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'APPROVED'; readonly value: 'APPROVED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
            ];
          };
          readonly PaymentStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PAID'; readonly value: 'PAID' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
